name: Flutter Deploy to Cloudflare and GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Verify Flutter environment
        run: flutter doctor

      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web --web-renderer html --release

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: web-build
          path: build/web

  publish:
    name: Publish to Cloudflare & GitHub Pages
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: web-build
          path: build/web

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: zfont
          directory: build/web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: production
          wranglerVersion: '3'

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v5.0.0

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: build/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
